name: 'chicago_taxi_analysis'
version: '1.0.0'
config-version: 2

profile: 'chicago_taxi_analysis'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  chicago_taxi_analysis:
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold

vars:
  project_id: "{{ env_var('GCP_PROJECT_ID') }}"
  raw_dataset: "chicago_taxi_raw"
  silver_dataset: "chicago_taxi_silver"
  gold_dataset: "chicago_taxi_gold"
